name: build
on: 
  push:
jobs:
  build:
    name: my job
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node: [10, 12, 14]
    steps:
      - name: my first step
        env:
          MY_VAR: HI THERE! MY NAME IS
          FIRST_NAME: Miko
          MIDDLE_NAME: Mikenito
          LAST_NAME: Phantom
        run: |
          echo $MY_VAR
          echo $FIRST_NAME $MIDDLE_NAME $LAST_NAME
          
